arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot_b_waist
    - robot_b_shoulder
    - robot_b_elbow
    - robot_b_forearm_roll
    - robot_b_wrist_angle
    - robot_b_wrist_rotate
  constraints:
    goal_time: 1
    stopped_velocity_tolerance: 0.02

#gripper_controller:
#  type: position_controllers/JointTrajectoryController
#  joints:
#    - robot_b_left_finger
